apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-editor-deployment
spec:
  selector:
    matchLabels:
      app: eks-editor-app
  template:
    metadata:
      labels:
        app: eks-editor-app
    spec:
      containers:
      - name: eks-editor-app
        image: davegabe/image-editor:v7-release
        resources:
          requests:
            cpu: "512m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5100
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: eks-editor-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: eks-editor-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: eks-editor-secrets
              key: AWS_SESSION_TOKEN
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: eks-editor-secrets
              key: AWS_DEFAULT_REGION
