apiVersion: v1
kind: Service
metadata:
  name: eks-editor-service
  namespace: eks-editor-app-ns
spec:
  selector:
    app: eks-editor-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5100
  type: LoadBalancer